language: ruby
cache: bundler
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 2.2.2
deploy:
  provider: rubygems
  api_key:
    secure: CHANGEME
  gem: wavefront-ruby-client
  on:
    tags: true
    all_branches: true
    repo: wavefrontHQ/ruby-client
    ruby: 1.9.3
